class AppNamed {
  AppNamed._();

  static const String onboarding = '/onboarding';
  static const String login = '/login';
  static const String register = '/register';
  static const String signupSuccess = '/signup-success';
  static const String verifyEmailOtp = '/verify-email-otp';
  static const String forgotPassword = '/forgot-password';
  static const String resetPassword = '/reset-password';
  static const String menuPage = "/menu-page";
  static const String analyticsPage = "/analytics-page";
  static const String voucherPage = "/voucher-page";
  static const String profilePage = "/profile-page";
  static const String walletsDashboard = '/wallets-dashboard';
  static const String addNewCard = '/add-new-card';
  static const String topUpPage = '/top-up-page';
  static const String scannerPage = '/scanner-page';
  static const String myQrPage = '/my-qr-page';
  static const String transferPage = '/transfer';
  static const String transferByWalletPage = '/transfer-wallet';
  static const String transferByBankPage = '/transfer-bank';
  static const String editProfile = '/edit-profile';
  static const String paymentSecurity = '/payment-security';
  static const String notificationPage = '/notification';
  static const String withdrawPage = '/withdraw-page';
  static const String shareAnalysis = '/share-analysis';
  static const String setting = '/setting';
  static const String shareQr = '/share-qr';
  static const String shareBill = '/share-bill';
  static const String friends = '/friends';
  static const String addNewFriend = '/add-new-friend';
  static const String transactionSuccess = '/transaction-success';
  static const String voucherDeals = '/voucher-deals';
  static const String recentTransfers = '/recent-transfers';
  static const String utilityBills = '/utility-bills';
  static const String billDetails = '/bill-details';
  static const String allTransactions = '/all-transactions';
  static const String pinSetup = '/pin-setup';
}
